/******
 * Redux action constants.
 *
 ******/

/**
 * API Actions
 */
export const APP_LOGIN = 'app/LOGIN';
export const FETCH_INCOMPLETE_TASKS_START = 'app/FETCH_INCOMPLETE_TASKS_START';
export const FETCH_INCOMPLETE_TASKS_SUCCESS = 'app/FETCH_INCOMPLETE_TASKS_SUCCESS';
export const FETCH_COMPLETED_TASKS_START = 'app/FETCH_COMPLETED_TASKS_START';
export const FETCH_COMPLETED_TASKS_SUCCESS = 'app/FETCH_COMPLETED_TASKS_SUCCESS';
export const PUT_TASKS_START = 'app/PUT_TASKS_START';
export const PUT_TASKS_SUCCESS = 'app/PUT_TASKS_SUCCESS';
export const PUT_SINGLE_TASK_START = 'app/PUT_TASK_START';
export const PUT_SINGLE_TASK_SUCCESS = 'app/PUT_SINGLE_TASK_SUCCESS';
export const FETCH_INDIVIDUAL_TASK_START = 'app/FETCH_INDIVIDUAL_TASK_START';
export const FETCH_INDIVIDUAL_TASK_SUCCESS = 'app/FETCH_INDIVIDUAL_TASK_SUCCESS';

/**
 * Store Actions
 */
export const UPDATE_STORE_TODOS = 'app/UPDATE_STORE_TODOS';